<div class="results">
    <div class="wrapper">
        <div class="header">
            <h1>Home</h1>
        </div>
        <div class="statsWrapper">
            <a href="/index.php/words/" class="stats">
                <div>
                    <h2>Words</h2>
                    <p><?php echo $data['wordCount']; ?></p>
                </div>
            </a>

            <a href="/index.php/patterns/" class="stats">
                <div>
                    <h2>Patterns</h2>
                    <p><?php echo $data['patternCount']; ?></p>
                </div>


            <a href="#" class="stats" onclick="display()">
                <div>
                    <h2>Add New Record</h2>
                </div>
            </a>
        </div>