<div class="results">
    <div class="wrapper">
        <div class="header">
            <h1>Patterns</h1>
        </div>
        <?php foreach ($data['patterns'] as $id => $row): ?>
            <div class="showResultPattern" id="<?php echo $id; ?>">
                <div class="result"> <?php echo $row['pattern'] ?> </div>
                <div class="edit"><a href="#">Edit</a></div>
                <div class="delete"><a href="#">Delete</a></div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class='pagination'>
        <?php $page = $data['paginate']->paginate();?>
        <div class='next'><a href='/index.php/<?php echo $page['page']?>/<?php echo $page['nextPage'];?>'><i class="fas fa-arrow-right"></i></a></div>
        <div class='previous'><a href='/index.php/<?php echo $page['page']?>/<?php echo $page['prevPage'];?>'><i class="fas fa-arrow-left"></i></a></div>
        <div class="curPage"><?php echo "Page: " . $page['pageNumber']/10 . "/" . $data['numberOfPages'];?></div>
    </div>