<div class="formWrapper" id="submitForm">
    <form action="#" method="post" id="form">
        <label for="">Add New</label>
        <select name="table" id="select">
            <option value="words" id="selectWords">Word</option>
            <option value="patterns" id="selectPatterns">Pattern</option>
        </select>
        <input type="text" name="word" id="word" placeholder="Type here" autocomplete="off">
        <input type="submit" name="submit">
    </form>
</div>
</div>